fix encoding data with None values and more
jawah/niquests pull request #119
Opened 2024-05-03 18:53 UTC by karosc

This addresses #118, inspired by the code in [requests](https://github.com/psf/requests/blob/2d5f54779ad174035c5437b3b3c1146b0eaf60fe/src/requests/models.py#L122).

Essentially this PR will allow encoding any non-iterable object as string. This is a general solution to the specific problem in #118. Since `None` is not iterable, it is encoded "None". Similarly, any non-iterable object will be encoded as `str(obj)`.

2024-05-04 03:52 UTC, Ousret reviewed
the test only make sure the error does not occurs. we should verify that the "None" values are excluded.

2024-05-04 03:52 UTC, Ousret commented on tests/test_requests.py
> +    assert isinstance(p.body, str)
you should also check that the data (e.g. keys) must be present or not.
Add a test showing that "None" key is indeed absent.

2024-05-04 03:52 UTC, Ousret commented on tests/test_requests.py
> +        "plain_class": Class(),
what does Requests do here?

2024-05-04 04:01 UTC, Ousret commented on tests/test_requests.py
> +        "plain_class": Class(),
I don't think there any value having a str(nonstringableobj). we should do something about it.

2024-05-04 06:49 UTC, Ousret commented on tests/test_requests.py
> +    assert isinstance(p.body, str)
```python

import requests

if __name__ == "__main__":
    url = "https://httpbin.org/post"
    data = {'test_none': None, 'xx': 'hello'}

    # requests completes
    resp = requests.post(url, data=data)
    print(resp.json())

```

```
{'args': {}, 'data': '', 'files': {}, 'form': {'xx': 'hello'}, 'headers': {'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate, br', 'Content-Length': '8', 'Content-Type': 'application/x-www-form-urlencoded', 'Host': 'httpbin.org', 'User-Agent': 'python-requests/2.31.0', 'X-Amzn-Trace-Id': 'Root=1-6635da3e-494f137927479f5227ac558c'}, 'json': None, 'origin': '82.120.131.88', 'url': 'https://httpbin.org/post'}
```

`test_none` does not show up in result.

2024-05-04 20:21 UTC, karosc commented
@Ousret, you're totally right. I had how requests handles the `None` values totally wrong. I updated the PR and unit tests to check the values of the encoding as you suggested. I also wrote a short script to test that requests and niquests produce the same results when posting various python types:

```python
import niquests
import requests

class Class:
        pass

class ClassStringable:
    def __str__(self):
        return "🔥arbClassStringable🔥"

url = "https://httpbin.org/post"
body = {
    "string": "string",
    "float": 0.01,
    "int": 100,
    "bool": True,
    "None": None,
    "plain_class": Class(),
    "stringable_class": ClassStringable(),
}

resp_re = requests.post(url, data = body)
resp_ni = niquests.post(url, data = body)


for key in ['args', 'data','files','form','json']:
    try:
        assert resp_re.json()[key] == resp_ni.json()[key]
    except AssertionError:
        print(resp_re.json()[key],'\n\n\n',resp_ni.json()[key])
```

2024-05-05 03:51 UTC, Ousret requested changes
Almost there.

2024-05-05 03:51 UTC, Ousret commented on tests/test_requests.py
> +def test_data_ecodes_noniterables():
```suggestion
def test_data_encodes_noniterables(httpbin):
```

2024-05-05 03:51 UTC, Ousret commented on src/niquests/models.py
> +                    if not isinstance(vs, (str, bytes, type(None))):
```suggestion
                    if vs is not None and not isinstance(vs, (str, bytes,)):
```

2024-05-05 03:51 UTC, Ousret commented on tests/test_requests.py
> +    resp = niquests.post(url="https://httpbin.org/post", data=body)
```suggestion
    resp = niquests.post(httpbin("post"), data=body)
```

2024-05-05 03:52 UTC, Ousret commented on tests/test_requests.py
> +def test_data_ecodes_noniterables():
We must avoid internet access if not needed. This is a test that does not require HTTP/2+
Let's use the internal httpbin for it.

2024-05-05 03:53 UTC, Ousret commented on src/niquests/models.py
> +                    if not isinstance(vs, (str, bytes, type(None))):
This is more of a style consideration. We must check for None using the identity operator.

2024-05-05 03:55 UTC, Ousret commented on tests/test_requests.py
> +        "string": "string",
```suggestion
        "string": "string",
        "bytes": b"string",
```

2024-05-05 03:55 UTC, Ousret commented on tests/test_requests.py
> +        "string": "string",
```suggestion
        "string": "string",
        "bytes": "bytes",
```

2024-05-05 04:05 UTC, Ousret commented on tests/test_requests.py
> +        "bytes": "bytes",
```suggestion
        "bytes": "string",
```

2024-05-06 04:31 UTC, Ousret approved these changes

2024-05-06 04:31 UTC, merged